// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum Puzzle {
  Wordle
}

enum Status {
  Cancelled,
  Pending,
  Active,
  Complete
}

enum VerificationMethod {
  Contract,
  Eoa
}

enum WinScheme {
  FirstToSolve,
  HighScore,
  SoleSolver
}

enum Currency {
  Eth,
  ERC20
}
