// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameType } from "./tables/GameType.sol";
import { GameStatus } from "./tables/GameStatus.sol";
import { BuyIn } from "./tables/BuyIn.sol";
import { SubmissionWindow } from "./tables/SubmissionWindow.sol";
import { InviteExpiration } from "./tables/InviteExpiration.sol";
import { GameStartTime } from "./tables/GameStartTime.sol";
import { PuzzleMasterEoa } from "./tables/PuzzleMasterEoa.sol";
import { Player1 } from "./tables/Player1.sol";
import { Player2 } from "./tables/Player2.sol";
import { RematchCount } from "./tables/RematchCount.sol";
import { Solved } from "./tables/Solved.sol";
import { Balance } from "./tables/Balance.sol";
import { VoteRematch } from "./tables/VoteRematch.sol";
