// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { GameType, GameTypeTableId } from "./tables/GameType.sol";
import { GameStatus, GameStatusTableId } from "./tables/GameStatus.sol";
import { SubmissionWindow, SubmissionWindowTableId } from "./tables/SubmissionWindow.sol";
import { GameStartTime, GameStartTimeTableId } from "./tables/GameStartTime.sol";
import { GamePlayer, GamePlayerTableId } from "./tables/GamePlayer.sol";
import { Solved, SolvedTableId } from "./tables/Solved.sol";
import { Deposit, DepositTableId } from "./tables/Deposit.sol";
import { OtherPlayer, OtherPlayerTableId } from "./tables/OtherPlayer.sol";
