// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Puzzle } from "./../common.sol";

/**
 * @title IPuzzleGameCreationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPuzzleGameCreationSystem {
  function games__createGame(Puzzle puzzleType) external;
}
