// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISolePlayerToSolveBetSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISolePlayerToSolveBetSystem {
  function games__applyBetSystem() external;

  function games__deposit() external;

  function games__claim() external;
}
