// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITwoPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITwoPlayerSystem {
  function games__makeTwoPlayer(bytes32 gameId, address opponent) external;

  function games__join(bytes32 gameId) external;
}
