// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWakeupObjectiveCreationSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWakeupObjectiveCreationSystem {
  function newObjective(uint32 wakeupTime, int8 playerTimezoneHrs) external returns (bytes32);

  function getBaseReward(uint32 alarmTime) external pure returns (uint32);
}
